### ISSUE TITLE
Grunt open is not working

### ISSUE THREAD

**Issue by mdunbavan** [matt-bailey/generator-bones#11]
Hi,

I have set up and installed the generator and the files are all in the correct place.

When I type 'grunt open' it says "Starting connect web server on localhost:9000" and "Done without errors" but when I visit that url its a dead link. I know usually it would not close the connection like that so I wondered what I might be thats causing it to fail or not load the server?

Thanks,
Mark

**Comment by matt-bailey** [comment]
Hi @mdunbavan. Apologies, but this generator is really old now and I'm not able to support it. You're probably best off just using the default Yeoman webapp generator: https://github.com/yeoman/generator-webapp

**Comment by mdunbavan** [comment]
Hi Matt,

Can this generator do friendly urls for example getting rid of .html on
pages and having nested pages/posts?

Cheers
Mark

On Friday, May 15, 2015, Matt Bailey <notifications@github.com> wrote:

> Hi @mdunbavan <https://github.com/mdunbavan>. Apologies, but this
> generator is really old now and I'm not able to support it. You're probably
> best off just using the default Yeoman webapp generator:
> https://github.com/yeoman/generator-webapp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matt-bailey/generator-bones/issues/11#issuecomment-102492374>
> .
>


-- 
Sent from Gmail Mobile

**Comment by matt-bailey** [comment]
It uses https://github.com/assemble/assemble which is a static site
generator, so I would assume it can do what you want. As I said though,
this generator is really old now (as are the dependencies, including the
version of assemble) so I probably wouldn't advise you use it.

My advice would be to follow this tutorial of mine on how to use grunt,
http://mattbailey.io/a-beginners-guide-to-grunt-redux/, and then install
assemble as another grunt task and take it from there. Nice and clean and
up-to-date :)

Hope that helps.

**Comment by mdunbavan** [comment]
Hey Matt,

I wanted to use Middleman but the clients server says 'No', pain in the
ass....

Started using assemble, it looks like it was updated on github not so long
ago along with the generator. Its pretty awesome.

Cheers,
Mark

On Mon, May 18, 2015 at 4:00 PM, Matt Bailey <notifications@github.com>
wrote:

> It uses https://github.com/assemble/assemble which is a static site
> generator, so I would assume it can do what you want. As I said though,
> this generator is really old now (as are the dependencies, including the
> version of assemble) so I probably wouldn't advise you use it.
>
> My advice would be to follow this tutorial of mine on how to use grunt,
> http://mattbailey.io/a-beginners-guide-to-grunt-redux/, and then install
> assemble as another grunt task and take it from there. Nice and clean and
> up-to-date :)
>
> Hope that helps.
>
>
> On Sun, 17 May 2015 at 21:02 Mark Dunbavan <notifications@github.com>
> wrote:
>
> > Hi Matt,
> >
> > Can this generator do friendly urls for example getting rid of .html on
> > pages and having nested pages/posts?
> >
> > Cheers
> > Mark
> >
> > On Friday, May 15, 2015, Matt Bailey <notifications@github.com> wrote:
> >
> > > Hi @mdunbavan <https://github.com/mdunbavan>. Apologies, but this
> > > generator is really old now and I'm not able to support it. You're
> > probably
> > > best off just using the default Yeoman webapp generator:
> > > https://github.com/yeoman/generator-webapp
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/matt-bailey/generator-bones/issues/11#issuecomment-102492374
> > >
> > > .
> > >
> >
> >
> > --
> > Sent from Gmail Mobile
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/matt-bailey/generator-bones/issues/11#issuecomment-102844539
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matt-bailey/generator-bones/issues/11#issuecomment-103087787>
> .
>



-- 
Made by Mark | www.markdunbavan.co.uk | 07719178879

**Comment by matt-bailey** [comment]
Hey, no worries. I use Jekyll for my own site - less flexible, but less of
a headache to set up ;) Good luck!
